version: '3.3'

volumes:
  pg_data:
  static:
  media:
  data:

services:

  db:
    image: postgres:13
    restart: unless-stopped
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: vglazasmotri/foodgram_backend
    restart: unless-stopped
    env_file: .env
    volumes:
      - static:/backend_static/
      - media:/app/media/
      - data:/app/data/
    depends_on:
      - db

  frontend:
    image: vglazasmotri/foodgram_frontend
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - backend

  nginx:
    image: nginx:1.19.3
    restart: unless-stopped
    ports:
      - "${BACKEND_PORT}:${HTTP_PORT}"
    volumes:
      - static:/var/html/backend_static/
      - media:/var/html/media/
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
    depends_on:
      - frontend
